### ISSUE TITLE
Does the results of moment matching and MCMC are similar?

### ISSUE THREAD

**Issue by mo704507064** [jaztsong/PILCO-gpytorch#1]
Thanks for your contribution. I carefully read your code and have two questions. The first one is that the results of moment matching and MCMC are similar? The second one is the code " V = (torch.transpose(tiL, dim0=1,dim1=2) @ lb[:, :, None])[..., 0] * c[:, None]" in  https://github.com/jaztsong/PILCO-gpytorch/blob/94776d4a0501f01921929eaef10eb5cacadb122e/pilco/models/mgpr.py#L196.  According to the function in the thesis, I wonder there is a "s" to mutiply.

**Comment by jaztsong** [comment]
Thanks for your interest. If my recollection is right, there are a few equations in the original TensorFlow version that are different from the thesis. This equation may be one of them. This repo is almost a line-by-line re-implementation of the TensorFlow version. 

BTW, when writing this code, I noticed a few problems with the PILCO approach. For example, it can't solve the inverted pendulum problem. I would happy to discuss more details with you if you're interested.

**Comment by mo704507064** [comment]
Thanks for your reply. I run the Tensorflow version of pilco approach, where the inverted pendulum is solved. But you have to use the RBF controller not the LinearController. You can try to run the tensorflow version. BTW,  glad to talk with you and I wonder whether I can add your wechat?

**Comment by jaztsong** [comment]
Feel free to add me on WeChat. My WeChat username is same as the GitHub username.
